language: cpp

matrix:
  include:
  - os: linux
    env: CMakeArgs=""
    compiler: gcc
  - os: linux
    env: CMakeArgs=""
    compiler: clang
  - os: osx
    env: CMakeArgs=""
    compiler: gcc
  - os: osx
    env: CMakeArgs=""
    compiler: clang
  - os: linux
    env: CMakeArgs="-D CMAKE_SYSTEM_NAME=Windows -D CMAKE_C_COMPILER=x86-64-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=x86-64-w64-mingw32-g++"
    compiler: gcc
  - os: linux
    env: CMakeArgs="-D CMAKE_SYSTEM_NAME=Windows -D CMAKE_C_COMPILER=i686-w64-mingw32-gcc -D CMAKE_CXX_COMPILER=i686-w64-mingw32-g++"
    compiler: gcc

install:
- if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install doxygen gcc-mingw-w64-i686 gcc-mingw-w64-x86-64 g++-mingw-w64-i686 g++-mingw-w64-x86-64; fi
- if [ $TRAVIS_OS_NAME = osx ]; then brew install doxygen || (brew update && brew install doxygen); fi
- if [ -n "$CMakeArgs" ]; then unset CXX; unset CC; fi

before_script:
    - mkdir build
    - cd build
    - cmake $CMakeArgs ..

script:
    - make all

after_success:
    - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
           mkdir push;
           cd push;
           git init;
           git remote add origin https://marcustomlinson:$GITHUB_TOKEN@github.com/MarcusTomlinson/DSPatch.git;
           git checkout -b build/$TRAVIS_PULL_REQUEST_BRANCH;
           git pull origin build/$TRAVIS_PULL_REQUEST_BRANCH;
           rm -rf ./*;
           cp ../*.so ./;
           cp -r ../docs/html ./docs;
           git add -A;
           git commit -m "bump";
           git push --set-upstream origin build/$TRAVIS_PULL_REQUEST_BRANCH;
       fi'

