language: cpp

os:
    - linux
    - osx

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install doxygen libasound2-dev; fi
    - mkdir build
    - cd build
    - cmake ..

script:
    - make all

after_success:
    - mkdir push
    - cd push
    - cp ../docs/html ./docs
    - git init
    - git remote add origin https://marcustomlinson:$GITHUB_TOKEN@github.com/MarcusTomlinson/DSPatch.git
    - git checkout -b build
    - git add -A
    - git commit -m "update"
    - git push -f --set-upstream origin build
