language: cpp

os:
    - linux
    - osx

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install doxygen libasound2-dev ; fi
    - mkdir build
    - cd build
    - cmake ..

script:
    - make all
